// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDADMd4gBYyAPc0kYTtl-_F35cfgwzPRxU',
    appId: '1:453606565058:web:104ec0c31116425e28075b',
    messagingSenderId: '453606565058',
    projectId: 'sensorvisualization-a7126',
    authDomain: 'sensorvisualization-a7126.firebaseapp.com',
    storageBucket: 'sensorvisualization-a7126.firebasestorage.app',
    measurementId: 'G-3VDPDZ9HEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXy4zFt2di2-9ezjHdmKTDGNFSWbhvu7Y',
    appId: '1:453606565058:android:07f4693c1d6c2e3428075b',
    messagingSenderId: '453606565058',
    projectId: 'sensorvisualization-a7126',
    storageBucket: 'sensorvisualization-a7126.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDal-HnB18Vxw0NVxSORb3YVkjBH2Y4BOw',
    appId: '1:453606565058:ios:f193c883b08a903e28075b',
    messagingSenderId: '453606565058',
    projectId: 'sensorvisualization-a7126',
    storageBucket: 'sensorvisualization-a7126.firebasestorage.app',
    iosBundleId: 'com.example.sensorvisualization25jp223wer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDal-HnB18Vxw0NVxSORb3YVkjBH2Y4BOw',
    appId: '1:453606565058:ios:4dbb784d393ba40528075b',
    messagingSenderId: '453606565058',
    projectId: 'sensorvisualization-a7126',
    storageBucket: 'sensorvisualization-a7126.firebasestorage.app',
    iosBundleId: 'com.example.sensorvisualization',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDADMd4gBYyAPc0kYTtl-_F35cfgwzPRxU',
    appId: '1:453606565058:web:9b3019f909a1f04e28075b',
    messagingSenderId: '453606565058',
    projectId: 'sensorvisualization-a7126',
    authDomain: 'sensorvisualization-a7126.firebaseapp.com',
    storageBucket: 'sensorvisualization-a7126.firebasestorage.app',
    measurementId: 'G-QD9CQ7BDWG',
  );
}
